### ISSUE TITLE
Brick ps vita fat 3.65 Enso

### ISSUE THREAD

**Issue by YusteX** [SKGleba/PSP2-batteryFixer#11]
Hola muy buenas, descargue la version que tienen en autoplugin 2 y al instalar e iniciar, mi consola se reinicio y no encendio mas la bateria estaba al 100%, no carga, se pone el led naranja 1 segundo y se apaga ¿brick?

**Comment by SKGleba** [comment]
Dont use autoplugin, try running the tool again
