### ISSUE TITLE
Vita shuts down with half of battery

### ISSUE THREAD

**Issue by Lycidias93** [SKGleba/PSP2-batteryFixer#2]
I used this plugin and deleted it after reboot. Date/time needed to be changed. 
Now my Vita shuts down with 60% battery or so.
How to fix this?
Thanks

**Comment by SKGleba** [comment]
Was it charging/connected to a charger?

**Comment by Lycidias93** [comment]
No it Was not connected to the charger.. Now my Vita is charging til 91% and then it stops charging.. Will do a battery test later and then i see if it shuts down on a certain battery level

**Comment by Lycidias93** [comment]
Suddently the battery dropped from 91% to 33% in standby

**Comment by SKGleba** [comment]
leave it die, charge fully, rerun the plugin
