### ISSUE TITLE
Isnt PS+POWER+START+SELECT more convenient ?

### ISSUE THREAD

**Issue by KuromeSan** [SKGleba/PSP2-batteryFixer#3]
Not really a bug per say, but i feel like doing this key combination is faster than installing a plugin every time you want to reset the battery controller ...

**Comment by SKGleba** [comment]
The combination only cuts power to the battery chip, check in syscon- base+0x9C on fw 0x6A001C.
The plugin makes syscon tell the battery chip to reset itself and wipe all the flags. Thats why this plugin doesnt work with bic hw 0xFFXX (some slims).

Anyways, combo is the same as removing the battery, plugin is the same as replacing the chip with a new one.
Fun fact: at each update the call is done again, but sony fucked up the code so it does nothing...
