### ISSUE TITLE
Unsupported battery controller rev. 

### ISSUE THREAD

**Issue by Localhorst86** [SKGleba/PSP2-batteryFixer#5]
Hello there.

I tried running this tool on my PS VITA pch-2000 model, but I get an error:

CHKERR: Unsupported battery controller rev.

Here's the battery controller info:
Name: Abby
HW: 0xff01
FW: 0x11
DF: 0x7
BOOT: 0x2063ad40000ff01

Console Info
Current FW 3.60
Min FW 3.50
Ps tv emulation off
Secure state bit 0x1
Manuf. Mode no
Use qa psid no

Anything we can do about this?

**Comment by SKGleba** [comment]
nop, the chip just does have any reset command.
