### ISSUE TITLE
Error says: Unsupported battery controller rev.

### ISSUE THREAD

**Issue by leosel** [SKGleba/PSP2-batteryFixer#7]
Error says: Unsupported battery controller rev. Hold (pwr +ps+LT+SELECT+START) for the force system hard reset....
Why is this error means...and why my battery is unsupported?

**Comment by SKGleba** [comment]
The battery controller does not support the reset command, you may try forcing syscon reset with the key combo.

**Comment by leosel** [comment]
> The battery controller does not support the reset command, you may try forcing syscon reset with the key combo.

It doesn't work after doing the key combo

**Comment by leosel** [comment]
How can I determine if there's something wrong with my battery?
