### ISSUE TITLE
Unsupported battery controller rev.

### ISSUE THREAD

**Issue by leosel** [SKGleba/PSP2-batteryFixer#8]
Is there's something wrong with my battery if this error displays on your app?

**Comment by rand92000** [comment]
I would also like to know this, @SKGleba 
(Also - thank you for your work. :)

**Comment by dothackjhe** [comment]
I also seem to be getting a similar issue on the PS Vita Slim.

**Comment by RayCist1608** [comment]
I think it's an issue only on the slim

**Comment by SKGleba** [comment]
Will be fixed in the next update

**Comment by TootyFruityAnim** [comment]
yo when is the next update coming out? it's been a year

**Comment by SKGleba** [comment]
Hopefully next week.

**Comment by TootyFruityAnim** [comment]
bro its been 9 days and no update to vpk

**Comment by Sheikhm007** [comment]
The app still shows an error in the vita slims, when will it be fixed ?

**Comment by Brandon98SE** [comment]
Thanks for making this program, it just saved me money buying a new battery for my Red Japanese PS Vita my Mum got me for Christmas 2022! 👍 🥇

**Comment by SKGleba** [comment]
fixed in v3.0
